frr defaults traditional
hostname leaf1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.1.1/32
!
interface eth1
 ip address 10.0.0.1/31
!
interface eth2
 ip address 10.0.0.5/31
!
vrf vrf-ten1
 vni 50100
exit-vrf
!
router bgp 65101
 bgp router-id 10.255.1.1
 no bgp ebgp-requires-policy
 neighbor 10.0.0.0 remote-as 65000
 neighbor 10.0.0.0 bfd
 neighbor 10.0.0.4 remote-as 65000
 neighbor 10.0.0.4 bfd
 !
 address-family ipv4 unicast
  neighbor 10.0.0.0 activate
  neighbor 10.0.0.4 activate
  network 10.255.1.1/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.0.0 activate
  neighbor 10.0.0.4 activate
  advertise-all-vni
  advertise-default-gw
  advertise-svi-ip
 exit-address-family
!
router bgp 65101 vrf vrf-ten1
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 65102:50100
 exit-address-family
!
line vty
