frr defaults traditional
hostname leaf2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.1.2/32
!
interface eth1
 ip address 10.0.0.3/31
!
interface eth2
 ip address 10.0.0.7/31
!
vrf vrf-ten1
 vni 50100
exit-vrf
!
router bgp 65102
 bgp router-id 10.255.1.2
 no bgp ebgp-requires-policy
 neighbor 10.0.0.2 remote-as 65000
 neighbor 10.0.0.2 bfd
 neighbor 10.0.0.6 remote-as 65000
 neighbor 10.0.0.6 bfd
 !
 address-family ipv4 unicast
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.6 activate
  network 10.255.1.2/32
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.0.2 activate
  neighbor 10.0.0.6 activate
  advertise-all-vni
  advertise-default-gw
  advertise-svi-ip
 exit-address-family
!
router bgp 65102 vrf vrf-ten1
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 65101:50100
 exit-address-family
!
line vty
